Updated openai version and added GPT_4_TURBO
OpenBMB/ChatDev pull request #277
Opened 2023-11-18 21:51 UTC by zinccat

2023-11-19 18:50 UTC, yujingr approved these changes

2023-12-01 01:55 UTC, Alphamasterliu requested changes
Hello, thank you for your prompt support. However, there are some issues with the pull request you submitted that require your attention. Specifically, the modification you made in the camel/model_backend section:

diff
```
     try:
-        response = openai.ChatCompletion.create(*args, **kwargs, model=self.model_type.value, **self.model_config_dict)
+        response = openai.chat.completions.create(*args, **kwargs, model=self.model_type.value, **self.model_config_dict)
     except AttributeError:
         response = openai.chat.completions.create(*args, **kwargs, model=self.model_type.value, **self.model_config_dict)
```
We hope you can revert to the original method while ensuring compatibility for both versions, as your current direct change will cause many users to not be able to use the feature. Please pay special attention to such issues for future updates.

2023-12-05 09:48 UTC, rolltidehero commented
Damn... Hopefully this can get added soon. Really looking forward to this feature. Love everything you all do <3

2023-12-21 02:13 UTC, merged

2023-12-21 14:06 UTC, ysh-rawat-11 commented
Google bard has released Gemini Api what if it get sifted to geminai instead of gpt4 
https://ai.google.dev/docs/gemini_api_overview